public enum CardType {
    EARTHQUAKE,
    RECEIVE_MONEY,
    GIVE_OPPONENT_CASH,
    GIVE_OPPONENT_CITY,
    GO_BACK_THREE_SPACES,
    GO_TO_JAIL,
    OUT_OF_JAIL,
    TAX_REDUCE,
    CHAIRMAN,
    ADVANCE_TO_START,
    COLLECT_MONEY_FROM_OTHER_PLAYER,
    LUCKY_DRAW,
    PROPERTY_SWAP
}
